// Example Supabase Edge Function: verify-paystack
// This function verifies a Paystack transaction by reference, creates an
// enrollment row in the `enrollments` table, and sends a confirmation
// email via SendGrid. Deploy this function to your Supabase project and
// set the required secrets (see PAYMENT_SETUP.md).

import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
const PAYSTACK_SECRET = process.env.PAYSTACK_SECRET_KEY
const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY || !PAYSTACK_SECRET) {
  // In a deployed edge function you'd return an error response. For
  // local editing we throw so the missing config is obvious.
  throw new Error('Missing required environment variables for verify-paystack function')
}

const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

// Handler: depending on your runtime you may need to adapt the signature.
// This code assumes a Node/Express-like environment for clarity.
export default async function handler(req: any, res: any) {
  try {
    if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

    const { reference, course_id, student_id } = req.body
    if (!reference || !course_id || !student_id) {
      return res.status(400).json({ error: 'Missing parameters' })
    }

    // Verify transaction with Paystack
    const verifyUrl = `https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`
    const verifyRes = await fetch(verifyUrl, {
      method: 'GET',
      headers: { Authorization: `Bearer ${PAYSTACK_SECRET}` },
    })

    const verifyJson = await verifyRes.json()
    if (!verifyRes.ok || verifyJson.data?.status !== 'success') {
      return res.status(400).json({ success: false, message: 'Payment not successful', verifyJson })
    }

    // Insert enrollment (id autogenerated)
    const now = new Date().toISOString()
    const { error: insertErr } = await supabaseAdmin
      .from('enrollments')
      .insert([
        {
          student_id,
          course_id,
          payment_status: 'completed',
          payment_id: verifyJson.data.reference,
          progress_percentage: 0,
          completed_at: null,
          enrolled_at: now,
          created_at: now,
        },
      ])

    if (insertErr) {
      return res.status(500).json({ success: false, message: 'Failed to create enrollment', error: insertErr })
    }

    // Optionally increment course enrollment_count
    await supabaseAdmin.rpc('increment_course_enrollment_count', { course_id })

    // Send confirmation email via SendGrid (if key available)
    if (SENDGRID_API_KEY) {
      // fetch student email
      const { data: userRows } = await supabaseAdmin.from('users').select('email, full_name').eq('id', student_id).limit(1)
      const student = userRows?.[0]
      if (student?.email) {
        const mail = {
          personalizations: [
            {
              to: [{ email: student.email }],
              subject: 'Enrollment confirmed',
            },
          ],
          from: { email: 'no-reply@example.com', name: 'Cohort' },
          content: [
            {
              type: 'text/plain',
              value: `Hi ${student.full_name || ''},\n\nYour enrollment for course ${course_id} is confirmed. Reference: ${reference}`,
            },
          ],
        }

        await fetch('https://api.sendgrid.com/v3/mail/send', {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${SENDGRID_API_KEY}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(mail),
        })
      }
    }

    return res.status(200).json({ success: true })
  } catch (err: any) {
    console.error('verify-paystack error', err)
    return res.status(500).json({ success: false, error: String(err) })
  }
}
